### ISSUE TITLE
UX Brainstorming

### ISSUE THREAD

**Issue by NorhanZ** [ANTS-COIN/platform#16]
Here's a document where we will put our ideas:

https://docs.google.com/spreadsheets/d/1H7UPt61o5Vsg6uUgGzJ2zQHlyP48Uw9PMkF6bAN3ZUE/edit?usp=sharing

**Comment by Drmicrosoft** [comment]
https://uxplanet.org/gamification-mechanics-in-ux-smart-user-journey-e294a7a03ff3 @NorhanZ

**Comment by Drmicrosoft** [comment]
![Screenshot from 2020-08-25 10-51-16](https://user-images.githubusercontent.com/4147924/91154070-548fac80-e6c1-11ea-8604-47af73a97057.png)
![Screenshot from 2020-08-25 10-51-37](https://user-images.githubusercontent.com/4147924/91154072-55c0d980-e6c1-11ea-967b-29f0441ce63b.png)
![Screenshot from 2020-08-25 10-53-36](https://user-images.githubusercontent.com/4147924/91154073-56597000-e6c1-11ea-9b96-7a656c1cf119.png)

**Comment by NorhanZ** [comment]
Wire frame:

https://www.figma.com/file/kvrmyW0L3JJ9X9OrQztBnB/Registration?node-id=0%3A1

@Mo-Hossary, @MayElDardiry & @aamhegazy, please check it out!

**Comment by MayElDardiry** [comment]
> Wire frame:
> 
> https://www.figma.com/file/kvrmyW0L3JJ9X9OrQztBnB/Registration?node-id=0%3A1
> 
> @Mo-Hossary, @MayElDardiry & @aamhegazy, please check it out!

I really like it! I just have a couple of comments:
1. There is no need to have a separation between Graduate and Student because our users are earners. 
2. In the level of experience, we can use the 3rd party assessment to fill those _(We'll do it anyway next steps)_ but here it can show _"Take Quizz"_ which redirects them to LinkedIn quizzes for this certain skill.
3. You can combine the profile to have _"level of expertise"_ and _"area of development"_ to have both on the profile. 

**Last note:**
Since you already finished the brainstorming for this sprint, add your links and deliverables to the associated task issued to be able to close this one.

@NorhanZ @Mo-Hossary
