### ISSUE TITLE
As an unauthorized user I want to Create/Edit my profile

### ISSUE THREAD

**Issue by aamhegazy** [ANTS-COIN/platform#21]

**Comment by mansour91** [comment]
- **[Fisrt draft for the wire frame(whimsical)](https://whimsical.com/TaGPzCQGPnfofwNEArNRCG)**
- [**Figma UI/Wire frame**](https://www.figma.com/file/kvrmyW0L3JJ9X9OrQztBnB/Registration?node-id=0%3A1) 
- **[Brainstorming Spreadsheet with all pages description(AntsCoin UX)](https://docs.google.com/spreadsheets/d/1H7UPt61o5Vsg6uUgGzJ2zQHlyP48Uw9PMkF6bAN3ZUE/edit?usp=sharing)**

**Comment by mansour91** [comment]
### May's comments

1. There is no need to have a separation between Graduate and Student because our users are earners.
2. In the level of experience, we can use the 3rd party assessment to fill those (We'll do it anyway next steps) but here it can show "Take Quizz" which redirects them to LinkedIn quizzes for this certain skill.
3. You can combine the profile to have "level of expertise" and "area of development" to have both on the profile.
